language: cpp

os:
- linux

compiler:
- clang

env:
  matrix:
  - NODE_VERSION="0.10.33" JOBS=6 S3_URL=s3://mapbox/node-cpp11
  - NODE_VERSION="0.11.14" JOBS=6 S3_URL=s3://mapbox/node-cpp11
  global:
  - secure: "Z2ail/SjHgR1lrOjUDkJEjqfLPENxkxPHw5BozQeDLStdjIV6TFbWimhN4aliKjaR8d/dhXBQoU3PZxT09G9d7MEbWU6JlMh/8MxDdgk+xal9TYhUIZZMvx3ioGsK9pKQMPkQp3uIGeagZbhvcbF7MZmm33cC2t5xDx/h3ghuFI="
  - secure: "YvCJEs37Kh/KQ/9iKY3d/XvZeEDwWHGHFwlSuDG4u50pgmewm4n2/zXzNA2ZOF7cHnPDAFQ9S7ENgHPV+9YO+KWpK7O8ePCB6hE5ktHsmdZDg53dh7xxAeMzZ3Cc/RIBulYcq1enk2gNOa+nJAB7pICcYg0tInc5OqIC75axg64="
  - secure: "II07EH8qNtu97EY/VXlRwZ4EgzVShLS8gztXCFkLXCbdNWn+ZWOdAf0QIpgnFEGx8/M1QOLqQCmEaUyl6S9cs/yRg94wKtX6g4JQ3KRVNi7yn7TBYGBBKBAzB2rZP84I4LKBJZqJIQm1ZQcfEfJT+BlUd6vBH5Y6FJltHTKq5Yk="
  - secure: "FM2LKGe8UfXJeoqWnAk29Ib5yIIpKp221GZLgMSk0TanF2YWz+/dGTQu0kHyx1wlS+4zzzzNE9n4PMGcV1SUU5sbFfOL0bweIQwrjFPv0ayxGXqAptYm7BzXsCilGPYt9EKIz/Q78tVxnpyQZKnwLVAt6TCexQCburFPZjbkH7M="
before_install:
- platform=$(uname -s | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/")
- if [[ ${platform} == 'linux' ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;sudo
  apt-get update -y;sudo apt-get install -y libstdc++6; fi;
- if [[ ${platform} == 'darwin' ]]; then xcrun --sdk macosx --show-sdk-version; fi;
- if [[ "${CXX}" == 'g++' ]]; then export JOBS=2; sudo apt-get install gcc-4.8 g++-4.8;
  export CXX="$(which g++-4.8)"; export CC="$(which gcc-4.8)"; fi;
- if [[ "${CXX}" == 'clang++' ]]; then export JOBS=4; export CXX="$(which clang++)";
  export CC="$(which clang)"; fi;
- sudo apt-get install -y python-pip
- sudo pip install awscli

install:
- git clone https://github.com/joyent/node v${NODE_VERSION}
- cd v${NODE_VERSION}
- git checkout origin/v${NODE_VERSION}-release
- ./configure --prefix=/tmp/node-${NODE_VERSION}

before_script:
- make -j$JOBS node-v${NODE_VERSION}-${platform}-x64.tar.gz
- aws s3 cp --acl public-read node-v${NODE_VERSION}-${platform}-x64.tar.gz ${S3_URL}/v${NODE_VERSION}/node-v${NODE_VERSION}-${platform}-x64.tar.gz
- make node-v${NODE_VERSION}.tar.gz
- aws s3 cp --acl public-read node-v${NODE_VERSION}.tar.gz ${S3_URL}/v${NODE_VERSION}/node-v${NODE_VERSION}.tar.gz

script:
- cd ../ && ./update_shashums.sh
