language: cpp

os:
- linux

compiler:
- clang

env:
  matrix:
  - NODE_VERSION="0.10.33" JOBS=4 S3_URL=s3://mapbox/node-cpp11
  global:
  - secure: QWLkZJm5/wfsX8KpEmaATS2niYyNWxByv/u2eQIWq5ytkJoz0wBfGdRQiXdiU123qHF2vEJYA/jOUKPhGGNSSkYC93LmthpOF1PNRf/3i2R/oqtf0RH26p3ObPa/cO3xQKbQzk6QG8opEcoC54UK+5Zs+3z17jjYGHoUNFVlGGU=
  - secure: YkSU0N8N5EAnMCxSHC20Oc24Ednq0nh+ODBnZaHJYNNf6gX1zKgWi9fl7EpmhwPLJy6Pi/J+zDf3aiwB76SfIugdxVYdSwXbRpAaXgDvYATuNpq5YJC9DqZ8Ly3VSED4WKNE1DSLqfIyLpvcaddTRL5SIx0Dqs/YYIzoEEaPs0Q=

before_install:
- platform=$(uname -s | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/")
- if [[ ${platform} == 'linux' ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;sudo
  apt-get update -y;sudo apt-get install -y libstdc++6; fi;
- if [[ ${platform} == 'darwin' ]]; then xcrun --sdk macosx --show-sdk-version; fi;
- if [[ "${CXX}" == 'g++' ]]; then export JOBS=2; sudo apt-get install gcc-4.8 g++-4.8;
  export CXX="$(which g++-4.8)"; export CC="$(which gcc-4.8)"; fi;
- if [[ "${CXX}" == 'clang++' ]]; then export JOBS=4; export CXX="$(which clang++)";
  export CC="$(which clang)"; fi;

install:
- git clone https://github.com/joyent/node v${NODE_VERSION}
- cd v${NODE_VERSION}
- git checkout origin/v${NODE_VERSION}-release
- "./configure --prefix=/tmp/node-${NODE_VERSION}"
- make -j$JOBS

before_script:
- true

script:
- sudo apt-get install -y python-pip
- sudo pip install awscli
- cd ../ && ./update_shashums.sh
