os: Visual Studio 2014 CTP4

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

install:
  - git clone https://github.com/mapbox/node.git -b v0.10.33-nodecpp11-blockingio node
  - cd node
  - vcbuild %configuration% %platform% nosign

build: off
test: off
deploy: off