environment:
  matrix:
    #- vs_version: 12
    - vs_version: 14

# http://help.appveyor.com/discussions/questions/557-visual-studio-2014

os: Visual Studio 2014 CTP4

configuration:
  #- Debug
  - Release

platform:
  #- x86
  - x64

install:
  - set FINAL_ARCH=64
  - if "%platform%" == "x86" set FINAL_ARCH=32
  - .\settings-minimal.bat %FINAL_ARCH% %vs_version% %configuration%
  - scripts\build_node.bat

build: off
test: off
deploy: off