os: Visual Studio 2015

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

install:
  - git clone https://github.com/mapbox/node.git -b v0.10.40 node
  - cd node
  - vcbuild %configuration% %platform% nosign

build: off
test: off
deploy: off